// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://esilrggquwquqdkgfamh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaWxyZ2dxdXdxdXFka2dmYW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5MTYyOTUsImV4cCI6MjA0NzQ5MjI5NX0.2gXemu25TLMAUFFiWSfPfe3EwN1upfSrncUzcuqXA48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);